### ISSUE TITLE
SecurityException Settings key: <data_roaming>

### ISSUE THREAD

**Issue by a5k-x** [Judopay/JudoKit-Android#183]
**Version: 3.0.13**
**Android target 33**
### Stacktrace:
java.lang.SecurityException: Settings key: <data_roaming> is only readable to apps with targetSdkVersion lower than or equal to: 32
                                                                                                    	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3081)
                                                                                                    	at android.provider.Settings$Global.getStringForUser(Settings.java:16010)
                                                                                                    	at android.provider.Settings$Global.getString(Settings.java:15993)
                                                                                                    	at com.judopay.judo3ds2.parameters.provider.SettingsGlobalDeviceParametersProvider.<init>(SettingsGlobalDeviceParametersProvider.kt:82)
                                                                                                    	at com.judopay.judo3ds2.parameters.DeviceParametersGatheringServiceImpl.retrieveParameters(DeviceParametersGatheringServiceImpl.kt:40)
                                                                                                    	at com.judopay.judo3ds2.service.ThreeDS2ServiceImpl.initialize(ThreeDS2ServiceImpl.kt:42)
                                                                                                    	at com.judopay.judokit.android.service.CardTransactionManager.configureWith(CardTransactionManager.kt:140)
                                                                                                    	at com.judopay.judokit.android.ui.cardentry.CardEntryFragment.onActivityCreated(CardEntryFragment.kt:63)
                                                                                                    	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3028)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:578)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
                                                                                                    	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3034)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:578)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
                                                                                                    	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
                                                                                                    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
                                                                                                    	at android.app.Activity.performStart(Activity.java:8330)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3670)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by stefan-tudor** [comment]
Hi @a5k-x,
thank you for reporting this issue!
release [4.0.0](https://github.com/Judopay/JudoKit-Android/releases/tag/v4.0.0) should fix this problem.
